FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . ./auth

ENV PYTHONUNBUFFERED=1
EXPOSE 8080

CMD ["python", "-m", "auth.gateway"]
